import { IThread } from "../types/thread";

export const THREADS: IThread[] = [
   {
      id: 1,
      content: "Hello World",
      userId: 1,
      mainThreadId: undefined,
      createdAt: "2024-10-14T09:19:48.980Z",
      updatedAt: "2024-10-14T09:19:48.980Z",
      images: [
         {
            id: 1,
            url: "https://res.cloudinary.com/dobp85exm/image/upload/v1728897587/circle/luuc5az2csohltvh4mc7.jpg",
            threadId: 1,
         },
         {
            id: 3,
            url: "https://res.cloudinary.com/dobp85exm/image/upload/v1728897588/circle/jrbkscx6fhbdl27pwodf.png",
            threadId: 1,
         },
         {
            id: 2,
            url: "https://res.cloudinary.com/dobp85exm/image/upload/v1728897587/circle/xxdwi7s7a1uw60etkmho.jpg",
            threadId: 1,
         },
      ],
      user: {
         id: 1,
         username: "cundus",
         profile: {
            id: 1,
            fullname: "CUNCUN",
            avatar:
               "https://res.cloudinary.com/dobp85exm/image/upload/v1728915922/circle/waps0matrsk3mfcqro98.jpg",
            background:
               "https://res.cloudinary.com/dobp85exm/image/upload/v1728915736/circle/gwexmh3xny1sdsjljqau.jpg",
            bio: "aku tanpa mu bagaikan butiran ",
            userId: 1,
         },
      },
      _count: {
         replies: 1,
         likes: 0,
      },
   },
   {
      id: 3,
      content: "content 1",
      userId: 2,
      mainThreadId: undefined,
      createdAt: "2024-10-14T10:18:31.313Z",
      updatedAt: "2024-10-14T10:18:31.313Z",
      images: [],
      user: {
         id: 2,
         username: "cundus2",
         profile: {
            id: 2,
            fullname: "cundus aja",
            avatar: undefined,
            background: undefined,
            bio: undefined,
            userId: 2,
         },
      },
      _count: {
         replies: 0,
         likes: 0,
      },
   },
   {
      id: 4,
      content: "content 2",
      userId: 1,
      mainThreadId: undefined,
      createdAt: "2024-10-14T10:18:33.900Z",
      updatedAt: "2024-10-14T10:18:33.900Z",
      images: [],
      user: {
         id: 1,
         username: "cundus",
         profile: {
            id: 1,
            fullname: "CUNCUN",
            avatar:
               "https://res.cloudinary.com/dobp85exm/image/upload/v1728915922/circle/waps0matrsk3mfcqro98.jpg",
            background:
               "https://res.cloudinary.com/dobp85exm/image/upload/v1728915736/circle/gwexmh3xny1sdsjljqau.jpg",
            bio: "aku tanpa mu bagaikan butiran ",
            userId: 1,
         },
      },
      _count: {
         replies: 0,
         likes: 0,
      },
   },
   {
      id: 5,
      content: "content 3",
      userId: 3,
      mainThreadId: undefined,
      createdAt: "2024-10-14T10:18:37.425Z",
      updatedAt: "2024-10-14T10:18:37.425Z",
      images: [],
      user: {
         id: 3,
         username: "cundus3",
         profile: {
            id: 3,
            fullname: "cundus aja",
            avatar: undefined,
            background: undefined,
            bio: undefined,
            userId: 3,
         },
      },
      _count: {
         replies: 0,
         likes: 0,
      },
   },
   {
      id: 6,
      content: "content 4",
      userId: 3,
      mainThreadId: undefined,
      createdAt: "2024-10-14T10:18:40.568Z",
      updatedAt: "2024-10-14T10:18:40.568Z",
      images: [],
      user: {
         id: 3,
         username: "cundus3",
         profile: {
            id: 3,
            fullname: "cundus aja",
            avatar: undefined,
            background: undefined,
            bio: undefined,
            userId: 3,
         },
      },
      _count: {
         replies: 0,
         likes: 0,
      },
   },
   {
      id: 7,
      content: "content 5",
      userId: 3,
      mainThreadId: undefined,
      createdAt: "2024-10-14T10:18:43.013Z",
      updatedAt: "2024-10-14T10:18:43.013Z",
      images: [],
      user: {
         id: 3,
         username: "cundus3",
         profile: {
            id: 3,
            fullname: "cundus aja",
            avatar: undefined,
            background: undefined,
            bio: undefined,
            userId: 3,
         },
      },
      _count: {
         replies: 0,
         likes: 0,
      },
   },
   {
      id: 8,
      content: "asdasd",
      userId: 2,
      mainThreadId: undefined,
      createdAt: "2024-10-15T03:11:16.393Z",
      updatedAt: "2024-10-15T03:11:16.393Z",
      images: [],
      user: {
         id: 2,
         username: "cundus2",
         profile: {
            id: 2,
            fullname: "cundus aja",
            avatar: undefined,
            background: undefined,
            bio: undefined,
            userId: 2,
         },
      },
      _count: {
         replies: 0,
         likes: 0,
      },
   },
   {
      id: 9,
      content: "aaaaa",
      userId: 2,
      mainThreadId: undefined,
      createdAt: "2024-10-15T03:11:16.393Z",
      updatedAt: "2024-10-15T03:11:16.393Z",
      images: [],
      user: {
         id: 2,
         username: "cundus2",
         profile: {
            id: 2,
            fullname: "cundus aja",
            avatar: undefined,
            background: undefined,
            bio: undefined,
            userId: 2,
         },
      },
      _count: {
         replies: 0,
         likes: 0,
      },
   },
   {
      id: 10,
      content: "331",
      userId: 3,
      mainThreadId: undefined,
      createdAt: "2024-10-15T03:11:16.393Z",
      updatedAt: "2024-10-15T03:11:16.393Z",
      images: [],
      user: {
         id: 3,
         username: "cundus3",
         profile: {
            id: 3,
            fullname: "cundus aja",
            avatar: undefined,
            background: undefined,
            bio: undefined,
            userId: 3,
         },
      },
      _count: {
         replies: 0,
         likes: 0,
      },
   },
   {
      id: 11,
      content: "2222",
      userId: 2,
      mainThreadId: undefined,
      createdAt: "2024-10-15T03:11:16.393Z",
      updatedAt: "2024-10-15T03:11:16.393Z",
      images: [],
      user: {
         id: 2,
         username: "cundus2",
         profile: {
            id: 2,
            fullname: "cundus aja",
            avatar: undefined,
            background: undefined,
            bio: undefined,
            userId: 2,
         },
      },
      _count: {
         replies: 0,
         likes: 0,
      },
   },
];
